name: Run test cases

on: [push, pull_request]

jobs:

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: prepare
      run: |
        brew install curl zip unzip gnu-sed erlang openssl@1.1
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: install rebar3
      run: |
        curl -fsSL -o /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
        chmod +x /usr/local/bin/rebar3
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: run eunit
      run: |
        rebar3 eunit

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        builder:
          - 5.3-3
        otp:
          - 26.2.3-1
        elixir:
          - 1.15.7
        arch:
          - amd64
          - arm64
        os: 
          - ubuntu22.04
          - ubuntu20.04
          - ubuntu18.04
          - debian12
          - debian11
          - debian10
          - el9
          - el8
          - el7
          - amzn2
          - amzn2023

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      with:
        platforms: ${{ matrix.arch }}
    - name: run eunit
      run: |
        IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
        docker run --rm -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} $IMAGE bash -euc 'make eunit'
